public class BatchApex implements Database.Batchable<sObject> {
    // public (Database.QueryLocator | Iterable<sObject>) start(Database.BatchableContext bc) {
    //     // collect the batches of records or objects to be passed to execute
    // }
    // public void execute(Database.BatchableContext bc, List<P> records){
    //     // process each batch of records
    // }
    // public void finish(Database.BatchableContext bc){
    //     // execute any post-processing operations
    // }
    // // Invoking the class
    // MyBatchClass myBatchObject = new MyBatchClass();
    // Id batchId = Database.executeBatch(myBatchObject);
    // // optionally pass a second scope parameter 
    // Id batchId = Database.executeBatch(myBatchObject, 100);
    
    
    //Sample Batch Apex Code 
}
